### ISSUE TITLE
gtf.py NameError : name 'record' is not defined

### ISSUE THREAD

**Issue by shiny-prize** [bartongroup/d3pendr#2]
Hi, I am trying to reproduce the result of apa analysis of nanopore to use for further research.
I am following the pipeline of Simpson_Barton_FPA_NLRs github code.

Now, I have bam file and trying to assemble them and use d3pendr. And there is some problem.
I made an gtf file by command
`cat Araport11.gtf output.tmp.gtf | gffread -T -M -K -Q > merged_nanopore_tmp.gtf`

where output.tmp.gtf is made by
`stringtie -o output.tmp.gtf 35SFPA.bam col0.bam fpa8.bam -t -L`

And then use the d3pendr to do apa analysis as
`d3pendr -t "/data/Storage_DAS03/shinsy/FPA-long/bam/35SFPA.bam" -c "/data/Storage_DAS03/shinsy/FPA-long/bam/col0.bam" -a "/data/Storage_DAS03/shinsy/FPA-long/bam/merged_nanopore.gtf" -o "35SFPA_vs_col0" -p 24 --use-locus-tag --bootstraps 999 --min-read-overlap 0.2`

However, I got this error

"Traceback (most recent call last):
  File "/data/Storage_DAS02/home2/shinsy/.conda/envs/dorado/lib/python3.12/site-packages/joblib-1.4.2-py3.12.egg/joblib/parallel.py", line 1457, in dispatch_one_batch
    tasks = self._ready_batches.get(block=False)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/Storage_DAS02/home2/shinsy/.conda/envs/dorado/lib/python3.12/queue.py", line 168, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

  
  Traceback (most recent call last):
    File "/data/Storage_DAS02/home2/shinsy/.conda/envs/dorado/lib/python3.12/site-packages/d3pendr-0.1-py3.12.egg/d3pendr/gtf.py", line 67, in get_gtf_attribute
  AttributeError: 'NoneType' object has no attribute 'group'
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/data/Storage_DAS02/home2/shinsy/.conda/envs/dorado/bin/d3pendr", line 33, in <module>
      sys.exit(load_entry_point('d3pendr==0.1', 'console_scripts', 'd3pendr')())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/data/Storage_DAS02/home2/shinsy/.conda/envs/dorado/lib/python3.12/site-packages/click-8.1.7-py3.12.egg/click/core.py", line 1157, in __call__
      return self.main(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/data/Storage_DAS02/home2/shinsy/.conda/envs/dorado/lib/python3.12/site-packages/click-8.1.7-py3.12.egg/click/core.py", line 1078, in main
      rv = self.invoke(ctx)
           ^^^^^^^^^^^^^^^^
    File "/data/Storage_DAS02/home2/shinsy/.conda/envs/dorado/lib/python3.12/site-packages/click-8.1.7-py3.12.egg/click/core.py", line 1434, in invoke
      return ctx.invoke(self.callback, **ctx.params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/data/Storage_DAS02/home2/shinsy/.conda/envs/dorado/lib/python3.12/site-packages/click-8.1.7-py3.12.egg/click/core.py", line 783, in invoke
      return __callback(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/data/Storage_DAS02/home2/shinsy/.conda/envs/dorado/lib/python3.12/site-packages/d3pendr-0.1-py3.12.egg/d3pendr/main.py", line 58, in d3pendr
    File "/data/Storage_DAS02/home2/shinsy/.conda/envs/dorado/lib/python3.12/site-packages/d3pendr-0.1-py3.12.egg/d3pendr/d3pendr.py", line 130, in run_d3pendr
    File "/data/Storage_DAS02/home2/shinsy/.conda/envs/dorado/lib/python3.12/site-packages/joblib-1.4.2-py3.12.egg/joblib/parallel.py", line 2007, in __call__
      return output if self.return_generator else list(output)
                                                  ^^^^^^^^^^^^
    File "/data/Storage_DAS02/home2/shinsy/.conda/envs/dorado/lib/python3.12/site-packages/joblib-1.4.2-py3.12.egg/joblib/parallel.py", line 1650, in _get_outputs
      yield from self._retrieve()
    File "/data/Storage_DAS02/home2/shinsy/.conda/envs/dorado/lib/python3.12/site-packages/joblib-1.4.2-py3.12.egg/joblib/parallel.py", line 1754, in _retrieve
      self._raise_error_fast()
    File "/data/Storage_DAS02/home2/shinsy/.conda/envs/dorado/lib/python3.12/site-packages/joblib-1.4.2-py3.12.egg/joblib/parallel.py", line 1789, in _raise_error_fast
      error_job.get_result(self.timeout)
    File "/data/Storage_DAS02/home2/shinsy/.conda/envs/dorado/lib/python3.12/site-packages/joblib-1.4.2-py3.12.egg/joblib/parallel.py", line 745, in get_result
      return self._return_or_raise()
             ^^^^^^^^^^^^^^^^^^^^^^^
    File "/data/Storage_DAS02/home2/shinsy/.conda/envs/dorado/lib/python3.12/site-packages/joblib-1.4.2-py3.12.egg/joblib/parallel.py", line 763, in _return_or_raise
      raise self._result
    File "/data/Storage_DAS02/home2/shinsy/.conda/envs/dorado/lib/python3.12/site-packages/joblib-1.4.2-py3.12.egg/joblib/parallel.py", line 1469, in dispatch_one_batch
      islice = list(itertools.islice(iterator, big_batch_size))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/data/Storage_DAS02/home2/shinsy/.conda/envs/dorado/lib/python3.12/site-packages/d3pendr-0.1-py3.12.egg/d3pendr/d3pendr.py", line 132, in <genexpr>
    File "/data/Storage_DAS02/home2/shinsy/.conda/envs/dorado/lib/python3.12/site-packages/d3pendr-0.1-py3.12.egg/d3pendr/gtf.py", line 7, in chunk_gtf_records
    File "/data/Storage_DAS02/home2/shinsy/.conda/envs/dorado/lib/python3.12/site-packages/d3pendr-0.1-py3.12.egg/d3pendr/gtf.py", line 93, in gtf_iterator
    File "/data/Storage_DAS02/home2/shinsy/.conda/envs/dorado/lib/python3.12/site-packages/d3pendr-0.1-py3.12.egg/d3pendr/gtf.py", line 71, in get_gtf_attribute
  NameError: name 'record' is not defined"

Is there some error with my gtf file? 
Thank you.

**Comment by mparker2** [comment]
Hi, yes it looks like the attributes column of the gtf file is not in the expected format. All exon and CDS attributes should have at least the attribute "gene_id" (and preferably also "transcript_id") and they should be formatted as a semi colon separated list of tag value pairs, where the tag and value are separated by a space and the value is enclosed within double quotes, as described here:

https://www.ensembl.org/info/website/upload/gff.html

for example:
```
Chr1	Liftoff	transcript	7395	9663	.	+	.	transcript_id "AT1G01010.1"; gene_id "AT1G01010";
Chr1	Liftoff	exon	7395	7677	.	+	.	transcript_id "AT1G01010.1"; gene_id "AT1G01010";
Chr1	Liftoff	exon	7760	8040	.	+	.	transcript_id "AT1G01010.1"; gene_id "AT1G01010";
Chr1	Liftoff	exon	8250	8369	.	+	.	transcript_id "AT1G01010.1"; gene_id "AT1G01010";
Chr1	Liftoff	exon	8470	8859	.	+	.	transcript_id "AT1G01010.1"; gene_id "AT1G01010";
Chr1	Liftoff	exon	8938	9090	.	+	.	transcript_id "AT1G01010.1"; gene_id "AT1G01010";
Chr1	Liftoff	exon	9203	9663	.	+	.	transcript_id "AT1G01010.1"; gene_id "AT1G01010";
Chr1	Liftoff	CDS	7524	7677	.	+	0	transcript_id "AT1G01010.1"; gene_id "AT1G01010";
Chr1	Liftoff	CDS	7760	8040	.	+	2	transcript_id "AT1G01010.1"; gene_id "AT1G01010";
Chr1	Liftoff	CDS	8250	8369	.	+	0	transcript_id "AT1G01010.1"; gene_id "AT1G01010";
```

Sorry I realise the error handling could be much better. I have not worked on or used these scripts for quite some time. If your gtf file is not in the correct format you could also try using [gffread](https://github.com/gpertea/gffread) to convert it (try `gffread -T` to get gtf2 format).

**Comment by mparker2** [comment]
ah sorry I see that you are also using the locus tag option. This further requires that the gtf file has a "locus" tag which is generated by running ~~stringtie in a certain way~~ gffread with the -M option to cluster overlapping transcripts into loci. But I see that you have actually already done this... Can you check that the stringtie GTFs include the locus tag?

**Comment by shiny-prize** [comment]
Thank you for your answer. Yes, I have the locus id in my gtf file. I have solved the issue by fix the code of the "get_gtf_attribute" function in gtf.py. I think the record variable is not assigned properly in line 71 and change it to gtf_record.

However, I have some more questions about analysis. Now, I am analyzing the raw data of nanopore and filtered.bam data from helicos. For the result of both data after using d3pendr, it is bit different from the publication.

I think there is some difference regarding reference genome and gtf file. May I get the reference and gtf file for further analysis? And if it is possible, for filtering nanopore data, seqeuence summary file is available? 

Thank you for your understanding.

**Comment by mparker2** [comment]
OK great, sorry about that.

The reference genome and annotation that we used was TAIR10 with the Araport11 annotation. I'm sorry that we did not make the GTF file from Stringtie available at publication, that was an oversight. I don't work at the Barton/Simpson group any more but I will try to get the GTF file and sequencing summary files for you. It may take me a few days, however.

**Comment by shiny-prize** [comment]
Could you send me GTF file, reference genome and sequencing summary file to my email, shinsy2013@snu.ac.kr?

Thank you for your hard work. It is really appreciated.

**Comment by shiny-prize** [comment]
Hello, When can you send the file?
